// <auto-generated />
using System;
using BarberShop.Infra.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberShop.Infra.Migrations
{
    [DbContext(typeof(BarberShopContext))]
    [Migration("20260404054923_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BarberShop.Domain.AccessControl.Module", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Edit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Exclude")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExclusionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Inactivate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Register")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Visualize")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Edit = true,
                            Exclude = true,
                            Inactivate = true,
                            Name = "Users",
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            Id = 2L,
                            Edit = true,
                            Exclude = true,
                            Inactivate = true,
                            Name = "Auth",
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            Id = 3L,
                            Edit = true,
                            Exclude = true,
                            Inactivate = true,
                            Name = "SendEmail",
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            Id = 4L,
                            Edit = true,
                            Exclude = true,
                            Inactivate = true,
                            Name = "Appointments",
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            Id = 5L,
                            Edit = true,
                            Exclude = true,
                            Inactivate = true,
                            Name = "Payments",
                            Register = true,
                            Visualize = true
                        });
                });

            modelBuilder.Entity("BarberShop.Domain.AccessControl.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExclusionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Admin",
                            Status = 1
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Cliente",
                            Status = 1
                        });
                });

            modelBuilder.Entity("BarberShop.Domain.AccessControl.ProfileModule", b =>
                {
                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Edit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Exclude")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Inactivate")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Register")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Visualize")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ModuleId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfilesModules", (string)null);

                    b.HasData(
                        new
                        {
                            ModuleId = 1L,
                            ProfileId = 1L,
                            Edit = true,
                            Exclude = true,
                            Inactivate = true,
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            ModuleId = 2L,
                            ProfileId = 1L,
                            Edit = true,
                            Exclude = true,
                            Inactivate = true,
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            ModuleId = 3L,
                            ProfileId = 1L,
                            Edit = true,
                            Exclude = true,
                            Inactivate = true,
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            ModuleId = 4L,
                            ProfileId = 1L,
                            Edit = true,
                            Exclude = true,
                            Inactivate = true,
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            ModuleId = 5L,
                            ProfileId = 1L,
                            Edit = true,
                            Exclude = true,
                            Inactivate = true,
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            ModuleId = 2L,
                            ProfileId = 2L,
                            Edit = false,
                            Exclude = false,
                            Inactivate = false,
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            ModuleId = 4L,
                            ProfileId = 2L,
                            Edit = false,
                            Exclude = false,
                            Inactivate = true,
                            Register = true,
                            Visualize = true
                        },
                        new
                        {
                            ModuleId = 5L,
                            ProfileId = 2L,
                            Edit = false,
                            Exclude = false,
                            Inactivate = false,
                            Register = true,
                            Visualize = true
                        });
                });

            modelBuilder.Entity("BarberShop.Domain.AccessControl.ProfileUser", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfilesUsers", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            ProfileId = 1L
                        });
                });

            modelBuilder.Entity("BarberShop.Domain.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExclusionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("BarberShop.Domain.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExclusionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("BarberShop.Domain.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExclusionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BarberShop.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExclusionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderId")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@barbershop.com",
                            Name = "Admin",
                            Password = "$2a$12$4sHQj3OUBgi.syi7oQwAf.TCbjhMzvqedwYnoVKPx5PVHR19siKKK",
                            Status = 1
                        });
                });

            modelBuilder.Entity("BarberShop.Domain.AccessControl.ProfileModule", b =>
                {
                    b.HasOne("BarberShop.Domain.AccessControl.Module", "Module")
                        .WithMany("ProfilesModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Domain.AccessControl.Profile", "Profile")
                        .WithMany("ProfilesModules")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("BarberShop.Domain.AccessControl.ProfileUser", b =>
                {
                    b.HasOne("BarberShop.Domain.AccessControl.Profile", "Profile")
                        .WithMany("ProfilesUsers")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Domain.User", "User")
                        .WithMany("ProfilesUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberShop.Domain.Appointment", b =>
                {
                    b.HasOne("BarberShop.Domain.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberShop.Domain.Payment", b =>
                {
                    b.HasOne("BarberShop.Domain.Appointment", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("BarberShop.Domain.Payment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("BarberShop.Domain.RefreshToken", b =>
                {
                    b.HasOne("BarberShop.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberShop.Domain.AccessControl.Module", b =>
                {
                    b.Navigation("ProfilesModules");
                });

            modelBuilder.Entity("BarberShop.Domain.AccessControl.Profile", b =>
                {
                    b.Navigation("ProfilesModules");

                    b.Navigation("ProfilesUsers");
                });

            modelBuilder.Entity("BarberShop.Domain.Appointment", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BarberShop.Domain.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ProfilesUsers");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
